### ISSUE TITLE
关于cv::rectangle画矩形框函数的问题

### ISSUE THREAD

**Issue by hehualin-tut** [linClubs/YOLOv8-TensorRT#11]
我按照readme目前一直到后处理阶段都没有问题，但是把最后的结果矩形框画在图像上并发布的时候就有了问题，cv::rectangle函数怎么都执行不了，甚至我手动定义的输入也会报错segmation fault (core dumped),目前也没找到是什么原因

**Comment by linClubs** [comment]
检查一下，你的结果向量中的框数量是否为空

**Comment by hehualin-tut** [comment]
已经解决，最后发现是ros catkin的opencv和jetpack中的opencv同时导入所导致的，在我忽略掉ros自带的oprncv后就没问题了> 检查一下，你的结果向量中的框数量是否为空

**Comment by linClubs** [comment]
解决了就好
