### ISSUE TITLE
编译的时候报错error: ‘class nvinfer1::ICudaEngine’ has no member named ‘getNbBindings’

### ISSUE THREAD

**Issue by cll-git** [linClubs/YOLOv8-TensorRT#12]
如题，报错 error: ‘class nvinfer1::ICudaEngine’ has no member named ‘getNbBindings’
在对应的头文件里确实没找到这个成员函数
CUDA 12.2
TensorRT 10.0
显卡3060

**Comment by linClubs** [comment]
tensorRT版本和cuda版本，我是在cuda11.3, Tensorrt8.6上开发

**Comment by cll-git** [comment]
> tensorRT版本和cuda版本，我是在cuda11.3, Tensorrt8.6上开发

谢谢，我降到11.4和8.5就能编译通过了
