### ISSUE TITLE
请问这个代码可以同时接收多个图像话题，同步处理嘛？

### ISSUE THREAD

**Issue by Pradur241** [linClubs/YOLOv8-TensorRT#8]
@linClubs  我现在是有5个摄像头，想一起跑分割。请问这种情况是需要单独写五个话题处理，还是消息同步后只调用一个引擎文件来处理呢？

**Comment by linClubs** [comment]
可以使用ros的message_filters、或者多线程处理搞5个队列，通过时间戳最近进行同步。

**Comment by Pradur241** [comment]
> 可以使用ros的message_filters、或者多线程处理搞5个队列，通过时间戳最近进行同步。

okk，谢谢大佬回复
